site_name: Squirrels Documentation
site_url: https://squirrels-nest.github.io/squirrels-docs/

theme: readthedocs
extra_css:
- static/style.css

nav:
- Home: index.md
- Overview: overview.md
- Tutorial:
  - Installation: tutorial/installation.md
  - 1. Initialize a Squirrels Project: tutorial/initialize.md
  - 2. Configure the Manifest File: tutorial/manifest.md
  - 3. Create the Dataset Parameters: tutorial/parameters.md
  - 4. Create the SQL Queries: tutorial/queries.md
  - 5. Activate the REST APIs & Test: tutorial/testapi.md
  - 6. Use the Context File: tutorial/context.md
  - What's Next?: tutorial/conclusion.md
- Command Line Reference:
  - init: cli/init.md
  - load-modules: cli/load-modules.md
  - credential management: cli/credentials.md
  - test: cli/test.md
  - run: cli/run.md
- Topic Guides:
  - Manifest File (squirrels.yaml): topics/manifest.md
  - Major vs Minor Version (Best Practices): topics/versioning.md
- How To...:
  - Configure Database Connections: how-to/database.md
  - Create Parameters: how-to/writing-parameters.md
  - Create Views with SQL and Jinja: how-to/sql-views.md
  - Create Views with Python: how-to/python-views.md
  - Design for Commonality and Variability: how-to/common-vary.md
  - Parameter Option Custom Fields: how-to/custom-fields.md
  - Modify Dates Using Squirrel's dateutils: how-to/modify-dates.md
- Front-End Reference:
  - Response Schema: front-end/response.md
  - Passing Parameter Selections: front-end/selections.md
  - Best Practices for Using REST API Response: front-end/best-practices.md
- Release Notes:
  - Version 0.1.1 (July 2, 2023): release-notes/v-0-1-1.md
  - Version 0.1.0 (June 11, 2023): release-notes/v-0-1-0.md

markdown_extensions:
- admonition
- attr_list
- md_in_html
