site_name: Squirrels Documentation
site_url: https://ty2huang.github.io/squirrels-docs/

theme: readthedocs

nav:
- Home: index.md
- Overview: overview.md
- Tutorial:
  - Installation: tutorial/installation.md
  - 1. Initialize a Squirrels Project: tutorial/initialize.md
  - 2. Configure the Manifest File: tutorial/manifest.md
  - 3. Create the Dataset Parameters: tutorial/parameters.md
  - 4. Create the SQL Queries: tutorial/queries.md
  - 5. Activate the REST APIs & Test: tutorial/testapi.md
  - 6. Use the Context File: tutorial/context.md
  - Final Thoughts: tutorial/conclusion.md
- Command Line Reference:
  - init: cli/init.md
  - load-modules: cli/load-modules.md
  - credential management: cli/credentials.md
  - test: cli/test.md
  - run: cli/run.md
- How To...:
  - Configure Database Connections: how-to/database.md
  - Create Views with SQL and Jinja: how-to/sql-views.md
  - Create Views with Python: how-to/python-views.md
  - Design for Commonality and Variability: how-to/common-vary.md
- Front-End Reference:
  - Passing Parameter Selections: front-end/selections.md
  - Response Schema: front-end/response.md

markdown_extensions:
- admonition
